version: '3'

services:
  web:
    build: ./
    env_file:
      - .env
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./templates/:/etc/nginx/templates
    networks:
      - main_network

networks:
  main_network:
        name: main_network 
        external: true